### ISSUE TITLE
Please fix twitch ur bad 

### ISSUE THREAD

**Issue by twitch0001** [twitch0001/granitepy#6]
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "/home/twitch/.local/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/home/twitch/.local/lib/python3.7/site-packages/andesite/client.py", line 115, in update_handler
    await player._voice_state_update(data["d"])
  File "/home/twitch/.local/lib/python3.7/site-packages/andesite/player.py", line 49, in _voice_state_update
    self.channel_id = int(data["channel_id"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by twitch0001** [comment]
Fixed in commit referenced above.
